
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.sintatico;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int IDENT = 14;
  public static final int WHERE = 4;
  public static final int NUMBER = 15;
  public static final int GE = 7;
  public static final int SEMI = 6;
  public static final int STAR = 8;
  public static final int EOF = 0;
  public static final int EQ = 5;
  public static final int LE = 9;
  public static final int GT = 11;
  public static final int COMMA = 13;
  public static final int error = 1;
  public static final int SELECT = 2;
  public static final int FROM = 3;
  public static final int NE = 10;
  public static final int LT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "FROM",
  "WHERE",
  "EQ",
  "SEMI",
  "GE",
  "STAR",
  "LE",
  "NE",
  "GT",
  "LT",
  "COMMA",
  "IDENT",
  "NUMBER"
  };
}

